# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'currency-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for currency-app
     pod 'iOSDropDown'	

  target 'currency-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'currency-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
