# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'currency-app' do
	use_frameworks!
  	# Pods for currency-app
     	pod 'iOSDropDown'
     	pod 'SwiftyJSON', '4.2.0'	

  target 'currency-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'currency-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
